### ISSUE TITLE
Protect against multithreading

### ISSUE THREAD

**Issue by Airblader** [Airblader/xcb-util-xrm#5]

**Comment by psychon** [comment]
Current state:
- Several different databases used simultaneously from several threads are no problem (e.g. no static variables are used)
- The same database can only be used from a single thread at a time (well, querying the same database from several threads at a time is fine as well, just modifications aren't safe)

Options that I see:
- Document the current state and be done (No idea if querying a DB concurrently should be documented as safe or not)
- Use libpthread-stubs (this is what XCB does: libpthread-stubs provides no-op implementations of pthread-functions in a way so that if the real libpthread is loaded, that one is used instead; so single-threaded programs have no overhead, but multi-threaded ones are thread-safe (as long as no one tries to `dlopen()` libpthread (I can live with that assumption)))

Personally, I prefer option number 1. ;-)

**Comment by Airblader** [comment]
Yeah, I agree. Let's document it and be done with it. The idea for this issue comes from early development when state for the current query was stores in the database directly. We have long ditched doing things that way, for obvious reasons.
