### ISSUE TITLE
Backup https url for m4 submodule?

### ISSUE THREAD

**Issue by jwhendy** [Airblader/xcb-util-xrm#64]
Hello,

This is probably not worth your time and I figured it out, but with the default settings if one goes to install the submodules behind a firewall (well, in my case at least), the clone will fail due to the git protocol. The Arch AUR package already has http specified, but the build kept failing due to trying to pull `m4` from `git://anongit`. I found that by manually editing the `.gitmodules` file to use the following URL, it would work: https://anongit.freedesktop.org/git/xcb/util-common-m4.git/

Anyway, again, not a typical issue but just wondered if there was a way to set a "backup" URL. I've not encountered submodules before so this had me really racking my brain since nothing in the Arch `PKGBUILD` file said anything about `anongit`, just this github URL!

**Comment by Airblader** [comment]
First of all sorry for the late reply, but I've been sick. There's no *practical* reason I could think of that prevents us from changing the URL to use https. However, this is the kind of setup all XCB utilities share which is why I'd rather not change it and keep the common stuff… well, common. :-) In general I'd say the firewall configuration is to blame here, though I am fully aware that it's usually not within the person's power to change it. I'm also not aware of any feature that allows specifying a "backup" URL.

I think this issue will disappear over the next few months because distributions will distribute compiled binaries once i3 releases and building from source will then become unnecessary for the average user, so I'll opt to ignore this issue. Hope this is OK with you.

**Comment by jwhendy** [comment]
No problem at all, and was more to just bring up the potential issue as I'd never run into it before (main site set to `https` with a module (hadn't even heard of those!) set to `git:`. No problem and at least I learned something if I run into it again. Absolutely it's the [corporate] firewall. Never would have run into it at home (and indeed, I didn't when I installed `i3` the first time). Thanks.

**Comment by Airblader** [comment]
I'm also happy you reported it just in case somebody runs into the same issue!
